### ISSUE TITLE
Unable to find package 'GrowCreate.PipelineCRM'

### ISSUE THREAD

**Issue by rhyshamilton** [theotron/PipelineCRM#1]
Running:
- Visual Studio 2015 Community Edition as Administrator
- NuGet v.3.4.4.1231 

Installing PipelineCRM to an existing Umbraco 7 (v. 7.4.3) website using the recommended NuGet method (`install-package GrowCreate.PipelineCRM <project name>`) causes the following error:

`install-package : Unable to find package 'GrowCreate.PipelineCRM'`

Exception:

+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCom 
   mand

**Comment by rhyshamilton** [comment]
Swapping `install-package GrowCreate.PipelineCRM <project name>`for `Install-Package PipelineCRM` appears to work.

Source: https://www.nuget.org/packages/PipelineCRM

**Comment by harvzor** [comment]
@rhyshamilton Thanks for bringing attention to this. It has been fixed in the readme file: https://github.com/theotron/PipelineCRM/commit/dbe245f64782574805dfd3542fb46d4f535cbff9
