### ISSUE TITLE
Config option for Member type and Currency

### ISSUE THREAD

**Issue by akeilox** [theotron/PipelineCRM#10]
I cant seem to compile the source, still working on it but here I would like to feedback what I noticed so far;

a) if its possible to change the Member type in pipeline.config as it seems its hardcoded in file ContactApiController.cs and we have no Member type.

b) also when I select MemberCreate to False in the config, it uses the built-in database tables but the Pipeline Dashboard can not show the values from the internal db. Navigating to individual records seems to be working but the Dashboard values dont show up and drag-drop breaks, rendering the simple use-case of dashboard non operable. How to operate dashboard with MemberCreate set to false?

c) Currency seems to show up as Pound even though server regional settings is set to local, USD$.
I had to edit the .html in views etc angular to | currency:"USD$" as a hack job.
Would it be possible to have this in config?

ContactApiController.cs 
var newMember = memberService.CreateMemberWithIdentity(contact.Email, contact.Email, contact.Name, "Member");
_^

**Comment by akeilox** [comment]
I would like to add for point C, if I try to override the culture in web.config like
	    <globalization uiCulture="en" culture="en-US"  ..
  </system.web>

it still shows British pound in the UI.
I have checked the umbraco hostname and culture set to en-US default with inherit as well.

Is it possible to change it without recompiling the code?

Edit: it seems the currency field was coming from user default language under Users.
Changing that to US did fix the display of currency issue.

Nevertheless it would be great if currency can be added in the Config file for long term flexibility as User may be operating with different currency than their default.

**Comment by akeilox** [comment]
I would like to update my finding (for point b) that Lecoati.uskySlider conflicts with Pipeline, where the console shows error on drag function/event. Removing uskySlider makes the values in Pipeline dashboard visible with create member set to false.

I have noticed the our package of pipeline and the source differs a lot as there was some renaming, installing package from our then downloading source to update the DLL (lets say to update the Member type name) was not that easy.
It would be great if Member type is not hardcoded and moved to pipeline.config.

Thank you again for sharing this package, I believe I got caught with the transition period.

**Comment by theotron** [comment]
Hi @akeilox, thanks for your feedback!

1) Thanks for reporting - I will add a fix to the next commit, coming up shortly.

2) I can't really replicate this: It sounds like the issue has to do with a conflict with another plugin, which we can't really support. If you find a fix, by all means send us a pull request!

3) Pipeline (like the rest of Umbraco) will use the User's culture - if you set the current User to "English-US" values will show in USD.  If you would like to be able to set the currency centrally (or vary per opportunity), please raise a new feature request.

Cheers
Theo

**Comment by theotron** [comment]
(1) fixed on latest commit - closing issue
