### ISSUE TITLE
Activity demo code - uhangout

### ISSUE THREAD

**Issue by akeilox** [theotron/PipelineCRM#11]
While watching the uHangout I saw the really cool Activity page, as seen in sshot below.
I cant seem to find the sample code, could you share the Views code discussed in the uhangout, or the activity page?

![uhangout ep075 with theo paraskevopoulos pipeline crm](https://cloud.githubusercontent.com/assets/4035501/23093185/23c8a5d2-f617-11e6-81f6-57a6a6595a7c.png)

**Comment by theotron** [comment]
@akeilox No can do mate - implementation code is for paying customers. We got to put food on the table ;-) 

Closing issue.
