### ISSUE TITLE
Date format issues

### ISSUE THREAD

**Issue by xrisdoc** [theotron/PipelineCRM#14]
I have noticed that there seems to be an issue with the dates that are being saved for an Opportunity.

This happens for both the Created Date (DateCreated in db) and Closing Date (DateCompleted in db).

For example, if I select the following date: `02-04-2017` it gets saved to the database as `2002-04-19 23:00:00.000`

So, not only is the date saved completely wrong, it's also out by one hour, which I guess is due to the time zone of the client. I guess this this needs to be UTC?

I have managed to work around this by modifying the code where it is setting the $scope.pipeline.DateCreated property to a `moment` object.

I noticed that the value from the date picker ($scope.createdDatepicker.value) was in the format `YYYY-MM-DD` : `2017-04-02`, so I changed the format string passed to the `moment` constructor to match the format that the value was in.

I changed the following from:

```
$scope.pipeline.DateCreated = $scope.createdDatepicker.value ? moment($scope.createdDatepicker.value, 'DD-MM-YYYY') : '';
```

to

```
$scope.pipeline.DateCreated = $scope.createdDatepicker.value ? moment($scope.createdDatepicker.value, 'YYYY-MM-DD') : '';
```

This change gets me close to the date value that I was expecting to be saved to the database . However, this value was an hour out: `2017-04-01 23:00:00.000`. It should be `2017-04-02 00:00:00.000`

I then modified this further and changed it to the following:

```
$scope.pipeline.DateCreated = $scope.createdDatepicker.value ? moment.utc(new Date($scope.createdDatepicker.value)) : '';
```

This change seems to have fixed the issue and the date seems to be saving to the database as I would expect: `2017-04-02 00:00:00.000`

I suspect this issue may occur for other date fields/pickers in Pipeline as I believe a colleague of mine had issues with the Date field on a Task.

I am not that familiar with moment.js, so I'm not sure if the change I have made is the best approach or not. So, haven't submitted this change as a Pull Request yet.

**Comment by theotron** [comment]
@xrisdoc - thanks for the contribution. Merged in and issue looks fixed. 

Only small alteration, to ensure we always get a Date object:

`$scope.pipeline.DateCreated = new Date($scope.createdDatepicker.value ? moment.utc(new Date($scope.createdDatepicker.value)) : '');`

Thanks again!
Theo
