### ISSUE TITLE
Adding a task with reminders setting in the past

### ISSUE THREAD

**Issue by pgregorynz** [theotron/PipelineCRM#16]
When adding a task that has a due date or reminder the dates are saving incorrectly.

Steps.

On a opportunity we click add task.
Set description.
Tick is this a task?
Set a due date 20/6/2017 12:30pm
Set a reminder date of 20/6/2017 11:30pm

Save.

Task is overdue because the dates are being saved as

20/6/2012

The times, the day and the month are correct but the year is out by 5 years.

Im pretty sure it is the same problem as seen in this issue and MomentJS might be the way to solve it. https://github.com/theotron/PipelineCRM/issues/14

**Comment by theotron** [comment]
@pgregorynz this was indeed related to #16, so fixed with latest commit. I will update Nuget package shortly.
