### ISSUE TITLE
If you move an opportunity from any status to Unassigned it disappears

### ISSUE THREAD

**Issue by pgregorynz** [theotron/PipelineCRM#17]
if you have an opportunity in any status including Unassigned, and you move it and drop it on unassigned, that opportunity will disappear including the unassigned column, until a new opportunity arrives and you can see the unassigned column again.

The opportunity that disappeared, seems to have no status. Because if you move the new opportunity out, the faulty opportunity that disappeared earlier, with disappear again.

It does not show in the None section either. It seems that it loses all statuses?

**Comment by theotron** [comment]
@pgregorynz - well spotted! Fixed with latest commit.
