### ISSUE TITLE
Source code not compiling

### ISSUE THREAD

**Issue by gcapnias** [theotron/PipelineCRM#2]
Hi,

I tried to clone the project and build it, following the instructions. 

There are several .dlls missing, located in a folder that does not exist in the code tree: ..\..\Pipeline\Website\bin -> this path is outside the .git repository folder.

**Comment by theotron** [comment]
Hi George

We don't commit bin files - these are either created by the build or restored by nuget.  

Also, there is no Website folder in the source. Are you sure you cloned this exact repo?

Send me a screenshot of your VS output if the problem persists.

Thanks
Theo

**Comment by gcapnias** [comment]
Yes, I do understand you do not commit binary files on the repository.

Although, if you check the GrowCreate.PipelineCRM.csproj file (https://github.com/theotron/PipelineCRM/blob/master/GrowCreate.PipelineCRM/GrowCreate.PipelineCRM.csproj), you will find paths like: 

`..\..\Pipeline\Website\bin` instead of `..\packages\`

which are outside the git repository. 

There are several .dlls, that are not pointing to the packages folder, as they should, so the solution cannot be compiled.

**Comment by theotron** [comment]
I see it now - the project is referencing Umbraco DLLs which should be linked through Nuget.

Thanks for the bug report George - I will try to fix this weekend, but if you are in a hurry, you can remove and re-add the missing references from local copies.

Cheers
Theo

**Comment by gcapnias** [comment]
Hi,

There are some .dlls missing. I believe this is due to, belonging to a previous version of MVC (4 instead of 5).

And the Umbraco.Licensing.dll - I cannot find it somewhere...

George J.

**Comment by xrisdoc** [comment]
I have experienced the same issue. To quickly resolve this, I simply added a new Umbraco web application project, named "Website", to the solution and that seemed to have resolved most of the missing references. However, there were still a few others missing. 
- Microsoft.Web.Mvc.FixedDisplayModes.dll - I just removed this as i believe this is actually no longer required
- Umbraco.Licensing.dll - I also just removed this
- Microsoft.Web.XmlTransform.dll - I sourced this form a directory on my local machine 

```
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\Web\Microsoft.Web.XmlTransform.dll

or

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\Web\Microsoft.Web.XmlTransform.dll
```

This will do us for now. Although, the best option probably would be to link to the UmbracoCMS.Core files through the NuGet package installed within the GrowCreate.PipelineCRM project as theotron has suggested.

**Comment by harvzor** [comment]
This issue has been fixed in https://github.com/theotron/PipelineCRM/commit/e4c0eea4efbf20064f9710b8e654487a98d0ac8c.

I've come across the XmlTranform issue before when I found that my local system didn't even have it. I have taken the dll from the v14.0 directory on my local system and I have included it in this repository under `/packages/XmlTranform/`. I'm not sure this is best practice, but it should hopefully allow people to open the solution with any recent version of VS.

Please can you guys do a fresh pull and let me know if it's working for you too?

**Comment by xrisdoc** [comment]
Yeah, that all seems to build successfully straight away now.

Thanks!
