### ISSUE TITLE
Opportunities: "My board" does not appear

### ISSUE THREAD

**Issue by rhyshamilton** [theotron/PipelineCRM#6]
Within **Opportunities**, the "My board" (containing a list of Prospects)  does not appear. 

![myboard](https://cloud.githubusercontent.com/assets/23315610/20432623/f62dd024-ad97-11e6-9c34-cb4c2def0b0e.PNG)

Possibly related to this issue (https://github.com/theotron/PipelineCRM/issues/5).

**Comment by harvzor** [comment]
Are you talking about the daskboard "My board"? If you go to the start page (by clicking on PIPELINECRM above your tree in your image), then you should see all of your opportunities.

The URL should match `/umbraco/#/pipelineCrm`.

**Comment by rhyshamilton** [comment]
Yes - the dashboard "My board" does not display. The URL of the original screenshot matches `/umbraco/#/pipelineCrm`.

**Comment by rhyshamilton** [comment]
Double-checked my **Dashboard.config**. The relevant Pipeline CRM dashboard was missing. 

```
  <section alias="StartupPipelineCrmDashboardSection">
    <areas>
      <area>pipelineCrm</area>
    </areas>
    <tab caption="My board">
      <control>/app_plugins/PipelineCRM/backoffice/dashboards/pipelines.html</control>
    </tab>
  </section>
```
