### ISSUE TITLE
Error in `gulp pack`.

### ISSUE THREAD

**Issue by gcapnias** [theotron/PipelineCRM#7]
This is the `gulp pack` command output - there is an error produced:

D:\Projects\WorkInProgress\PipelineCRM>gulp pack
[17:25:47] Using gulpfile D:\Projects\WorkInProgress\PipelineCRM\gulpfile.js
[17:25:47] Starting 'styles'...
[17:25:47] Starting 'scripts'...
[17:25:47] Starting 'nugetPack'...
[17:25:48] gulp-notify: [Gulp notification] Scripts task completed
[17:25:48] Finished 'scripts' after 1.15 s
[17:25:48] gulp-notify: [Gulp notification] Styles task completed
[17:25:48] Finished 'styles' after 1.21 s
[17:25:48] Finished 'nugetPack' after 1.35 s
[17:25:48] Starting 'pack'...
[17:25:48] Finished 'pack' after 26 μs
[17:25:48] gulp-notify: [Error in notifier] Error in plugin 'gulp-notify'
Message:
    Command failed: D:\Projects\WorkInProgress\PipelineCRM\node_modules\node-notifier\vendor\toaster\toast.exe -p D:\Projects\WorkInProgress\PipelineCRM\node_modules\gulp-notify\assets\gulp.png -m Scripts task completed -t Gulp notification -q true

Unhandled Exception: System.Exception: SQLITE_CONSTRAINT_UNIQUE (Exception from HRESULT: 0x87AF0813)
   at Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
   at toast.Program.ShowToast(String title, String message, String imageURI, Boolean sound)
   at toast.Program.Main(String[] args)

Details:
    killed: false
    code: 3762504530
    signal: null
    cmd: D:\Projects\WorkInProgress\PipelineCRM\node_modules\node-notifier\vendor\toaster\toast.exe -p D:\Projects\WorkInProgress\PipelineCRM\node_modules\gulp-notify\assets\gulp.png -m Scripts task completed -t Gulp notification -q true
WARNING: Option 'Verbose' has been deprecated. Use 'Verbosity' instead.
Attempting to build package from 'Package.nuspec'.

Id: PipelineCRM
Version: 1.0.0
Authors: Theo Paraskevopoulos
Description: A CRM package for the Umbraco 7 back-office
License Url: http://www.growcreate.co.uk/pipeline-crm-eula/
Project Url: http://growcreate.co.uk/
Tags: Umbraco CRM content management system GrowCreate
Dependencies: UmbracoCms (� 7.0.0)

Added file 'content\App_Plugins\PipelineCRM\backoffice\dashboards\mytasks.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\dashboards\pipelines.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\pipelineCrmTree\browse.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\pipelineCrmTree\contacts.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\pipelineCrmTree\delete.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\pipelineCrmTree\edit.contact.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\pipelineCrmTree\edit.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\pipelineCrmTree\edit.organisation.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\pipelineCrmTree\edit.segment.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\pipelineCrmTree\organisations.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\pipelineCrmTree\segments.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\pipelineCrmTree\settings.html'.
Added file 'content\App_Plugins\PipelineCRM\backoffice\pipelineCrmTree\tasks.html'.
Added file 'content\App_Plugins\PipelineCRM\dialogs\contact.add.html'.
Added file 'content\App_Plugins\PipelineCRM\dialogs\contact.select.html'.
Added file 'content\App_Plugins\PipelineCRM\dialogs\delete.confirm.html'.
Added file 'content\App_Plugins\PipelineCRM\dialogs\organisation.add.html'.
Added file 'content\App_Plugins\PipelineCRM\dialogs\organisation.select.html'.
Added file 'content\App_Plugins\PipelineCRM\dialogs\pipeline.add.html'.
Added file 'content\App_Plugins\PipelineCRM\dialogs\pipeline.summary.html'.
Added file 'content\App_Plugins\PipelineCRM\dialogs\task.add.html'.
Added file 'content\App_Plugins\PipelineCRM\dialogs\task.share.html'.
Added file 'content\App_Plugins\PipelineCRM\lang\en.xml'.
Added file 'content\App_Plugins\PipelineCRM\package.manifest'.
Added file 'content\App_Plugins\PipelineCRM\pipeline.min.js'.
Added file 'content\App_Plugins\PipelineCRM\PipelineCRM-icon.png'.
Added file 'content\App_Plugins\PipelineCRM\temp\dashboard.config.install.xdt'.
Added file 'content\App_Plugins\PipelineCRM\temp\pipeline.config.install.xdt'.
Added file 'content\App_Plugins\PipelineCRM\temp\umbracoSettings.config.install.xdt'.
Added file 'content\App_Plugins\PipelineCRM\temp\web.config.install.xdt'.
Added file 'content\App_Plugins\PipelineCRM\views\grid_contacts.html'.
Added file 'content\App_Plugins\PipelineCRM\views\grid_organisations.html'.
Added file 'content\App_Plugins\PipelineCRM\views\grid_pipelines.html'.
Added file 'content\App_Plugins\PipelineCRM\views\grid_segments.html'.
Added file 'content\App_Plugins\PipelineCRM\views\timeline.html'.
Added file 'content\Config\Dashboard.config.transform'.
Added file 'content\Config\pipeline.config'.
Added file 'content\Config\umbracoSettings.config.transform'.
Added file 'content\Web.config.transform'.
Added file 'how-to-package.xml'.
Added file 'lib\net45\GrowCreate.PipelineCRM.dll'.
Added file 'lib\net45\GrowCreate.PipelineCRM.pdb'.
Added file 'readme.txt'.

Successfully created package 'D:\Projects\WorkInProgress\PipelineCRM\PipelineCRM.1.0.0.nupkg'.

**Comment by xrisdoc** [comment]
I got that error too, the first time I ran it. I ran it again a second time and it seemed to run OK after that.

Did you try it again? Is the same thing happening again?

**Comment by gcapnias** [comment]
You are right - it didn't happen, when I run the command again...

**Comment by harvzor** [comment]
@xrisdoc @gcapnias Can you both give me your node, npm and gulp versions?

I'm running on:
node 6.2.1
npm 1.4.9
gulp 3.9.1

I deleted my `node_modules` folder, re ran `npm install` and then ran `gulp pack`. The pack went as expected, no errors occurred.

The errors you both got are simply to do with the toast notification part of the pack (informing you that the pack has completed). It's note exactly important but it would be nice if it worked for everyone.

I assume running `gulp` on the first run also gets this error? The `gulp` command also makes use of the toast notifications.

**Comment by xrisdoc** [comment]
I'm running on:
- node 6.9.1
- npm 3.10.8
- gulp 3.9.1

I tried it again by deleting the `node_modules` folder and re ran `npm install` and `gulp pack` just as you did and did not get any errors this time.

Also, did this a second time running `gulp` instead of `gulp pack` and that all seemed OK too.

It was just that once I got that error after I had first cloned the repo. Haven't got that error since.

When I next do a fresh clone of the repo I'll be sure to keep an eye out for that again at that point too.

**Comment by gcapnias** [comment]
I'm running on:
- node 4.5.0
- npm 3.10.6
- gulp 3.9.1

**Comment by harvzor** [comment]
@xrisdoc @gcapnias Which OS are you guys running? The error looks like it's to do with Windows.

**Comment by xrisdoc** [comment]
Yeah, Im running Windows 10 (Enterprise), but within a Parallels VM on Mac OSX.

All of this is done on the Windows 10 side though.

**Comment by theotron** [comment]
Closing for now - please reopen if there is something new.
