### ISSUE TITLE
Usability bug with Multi-Node Tree Picker in custom document type.

### ISSUE THREAD

**Issue by SouthCentralCode** [theotron/PipelineCRM#8]
After adding a standard multi-node tree picker data type to pipelineContact document type, when you click to select content nodes of said Picker in a contact instance in the right hand side in the slide out pane, the pane closes quickly, allowing you to only select a single node.  If you are quick you can select 2 nodes, and the selection persists after the pane disappears and is correctly saved (on save of the contact).  I have also noticed that there is no option to Add to the Picker that usually appears beneath the list, you can only select an existing node that then deletes it and then the pane opens again for selection. I have tried this with various different contact instances and documentType fields and it always occurs.

**Comment by theotron** [comment]
Fixed - you should be able to use Multi Tree Node Picker.
