### ISSUE TITLE
Ability to choose owner of a opportunity when creating

### ISSUE THREAD

**Issue by sbozzie** [theotron/PipelineCRM#9]
As a user, it would be great to be able to pick the owner of an opportunity on creation, or have it default to myself rather than default to the first Umbraco user (admin in my case)

**Comment by theotron** [comment]
I fixed the bug where only the Admin was showing on the Owner menu

Did you mean that you want to set the Owner on the 'Create Opportunity' dialog as well?

![image](https://cloud.githubusercontent.com/assets/1209089/21955891/4da298fc-da6c-11e6-9cd6-1bcfca7d7fad.png)

**Comment by sbozzie** [comment]
Yes, within the dialog would be ideal.

**Comment by theotron** [comment]
Added to latest commit - closing issue.
